# Generated by Django 4.2.17 on 2025-01-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "configure_name",
                    models.CharField(max_length=50, null=True, unique=True),
                ),
                ("ACCESS_TOKEN", models.TextField(null=True)),
                ("APP_ID", models.CharField(max_length=200, null=True)),
                ("APP_SECRET", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SaveRawAdsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform_name", models.CharField(max_length=100, null=True)),
                ("ad_id", models.CharField(max_length=255)),
                ("ad_name", models.CharField(max_length=255, null=True)),
                ("status", models.CharField(max_length=50, null=True)),
                ("effective_status", models.CharField(max_length=50, null=True)),
                ("created_time", models.DateTimeField(null=True)),
                ("updated_time", models.DateTimeField(null=True)),
                ("creative_id", models.CharField(max_length=255, null=True)),
                ("creative_name", models.CharField(max_length=255, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("video_id", models.CharField(blank=True, max_length=255, null=True)),
                ("thumbnail_url", models.URLField(blank=True, null=True)),
                ("raw_data", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("platform_name", "ad_id")},
            },
        ),
    ]
