# Generated by Django 4.2.17 on 2025-01-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("configure_name", models.CharField(max_length=50, null=True)),
                ("ACCESS_TOKEN", models.TextField(null=True)),
                ("APP_ID", models.CharField(max_length=200, null=True)),
                ("APP_SECRET", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SaveRawAdsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform_name", models.CharField(max_length=100, null=True)),
                ("raw_data", models.JSONField(null=True)),
            ],
        ),
    ]
