# Generated by Django 4.2.17 on 2025-01-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configure",
            name="configure_name",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
