# Generated by Django 4.2.17 on 2025-01-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0002_alter_configure_configure_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="saverawadsdata",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
